--
DROP TABLE VIDEO IF EXISTS;

--
DROP SEQUENCE SEQ_VIDEO IF EXISTS;

--
CREATE SEQUENCE SEQ_VIDEO START WITH 20 INCREMENT BY 1;

CREATE TABLE VIDEO (
ID BIGINT PRIMARY KEY,
MOVIE_TITLE VARCHAR(255) NOT NULL,
IS_CHECKED_OUT BOOLEAN DEFAULT FALSE NOT NULL,
RATING NUMERIC (19, 2),
);


